name: pdf_data_extractor
description: "{{PLACEHOLDER}}"
version: 0.0.1
repository: https://github.com/infumia/pdf_data_extractor/

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0

dev_dependencies:
  test: ^1.25.6
  flint: ^2.14.0
  melos: ^7.1.1
  custom_lint: ^0.8.0
  analyzer: ^8.1.1

melos:
  scripts:
    fix:
      run: dart fix --apply && dart format .
      exec:
        concurrency: 4
    format:
      run: dart format .
      exec:
        concurrency: 4
    upgrade:
      run: dart pub upgrade --major-versions
      exec:
        concurrency: 4
    get:
      run: flutter pub get
      exec:
        concurrency: 4
    flutter_clean:
      run: flutter clean
      exec:
        concurrency: 4
    cache_repair:
      run: flutter pub cache repair
